{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Heroes Of Pymoli Data Analysis\n",
    "* Of the 1163 active players, the vast majority are male (84%). There also exists, a smaller, but notable proportion of female players (14%).\n",
    "\n",
    "* Our peak age demographic falls between 20-24 (44.8%) with secondary groups falling between 15-19 (18.60%) and 25-29 (13.4%).  \n",
    "-----"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Note\n",
    "* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 549,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Index(['Purchase ID', 'SN', 'Age', 'Gender', 'Item ID', 'Item Name', 'Price'], dtype='object')"
      ]
     },
     "execution_count": 549,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Dependencies and Setup\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "# File to Load (Remember to Change These)\n",
    "file_to_load = \"Resources/purchase_data.csv\"\n",
    "\n",
    "# Read Purchasing File and store into Pandas data frame\n",
    "purchase_data = pd.read_csv(file_to_load)\n",
    "purchase_data.columns"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Player Count"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "* Display the total number of players\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 414,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Total Players</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>SN</th>\n",
       "      <td>576</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    Total Players\n",
       "SN            576"
      ]
     },
     "execution_count": 414,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "total_players = purchase_data['SN'].value_counts()\n",
    "total_players = pd.DataFrame(total_players)\n",
    "total_players.count()\n",
    "total_players = pd.DataFrame({\"Total Players\" :total_players.count()})\n",
    "total_players"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Purchasing Analysis (Total)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "* Run basic calculations to obtain number of unique items, average price, etc.\n",
    "\n",
    "\n",
    "* Create a summary data frame to hold the results\n",
    "\n",
    "\n",
    "* Optional: give the displayed data cleaner formatting\n",
    "\n",
    "\n",
    "* Display the summary data frame\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 415,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Number of Unique Items</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Item ID</th>\n",
       "      <td>183</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         Number of Unique Items\n",
       "Item ID                     183"
      ]
     },
     "execution_count": 415,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "item_count = purchase_data[\"Item ID\"].value_counts()\n",
    "item_count = pd.DataFrame(item_count)\n",
    "item_count = item_count.count()\n",
    "item_count_df = pd.DataFrame({\"Number of Unique Items\" :item_count})\n",
    "item_count_df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 416,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "3.050987179487176"
      ]
     },
     "execution_count": 416,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "average_price = purchase_data[\"Price\"].mean()\n",
    "average_price"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 417,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "780"
      ]
     },
     "execution_count": 417,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "number_of_purchases = purchase_data[\"Item ID\"].count()\n",
    "number_of_purchases"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 418,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "2379.77"
      ]
     },
     "execution_count": 418,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "total_revenue = purchase_data[\"Price\"].sum()\n",
    "total_revenue"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 419,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Number of Unique items</th>\n",
       "      <th>Average Price</th>\n",
       "      <th>Total Revenue</th>\n",
       "      <th>Number of Purchases</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Item ID</th>\n",
       "      <td>183</td>\n",
       "      <td>3.050987</td>\n",
       "      <td>2379.77</td>\n",
       "      <td>780</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         Number of Unique items  Average Price  Total Revenue  \\\n",
       "Item ID                     183       3.050987        2379.77   \n",
       "\n",
       "         Number of Purchases  \n",
       "Item ID                  780  "
      ]
     },
     "execution_count": 419,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "purchasing_analysis = pd.DataFrame()\n",
    "purchasing_analysis[\"Number of Unique items\"] = item_count_df['Number of Unique Items']\n",
    "purchasing_analysis[\"Average Price\"] = average_price\n",
    "purchasing_analysis[\"Total Revenue\"] = total_revenue\n",
    "purchasing_analysis[\"Number of Purchases\"] = number_of_purchases\n",
    "purchasing_analysis"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Gender Demographics"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "* Percentage and Count of Male Players\n",
    "\n",
    "\n",
    "* Percentage and Count of Female Players\n",
    "\n",
    "\n",
    "* Percentage and Count of Other / Non-Disclosed\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 420,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Gender</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Male</th>\n",
       "      <td>484</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Female</th>\n",
       "      <td>81</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Other / Non-Disclosed</th>\n",
       "      <td>11</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                       Gender\n",
       "Male                      484\n",
       "Female                     81\n",
       "Other / Non-Disclosed      11"
      ]
     },
     "execution_count": 420,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "player_gender = purchase_data[[\"SN\",\"Gender\"]]\n",
    "player_gender = player_gender.drop_duplicates(\"SN\")\n",
    "gender_demo = pd.DataFrame(player_gender[\"Gender\"].value_counts())\n",
    "gender_demo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 421,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Gender</th>\n",
       "      <th>Percentage of Players</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Male</th>\n",
       "      <td>484</td>\n",
       "      <td>84.027778</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Female</th>\n",
       "      <td>81</td>\n",
       "      <td>14.062500</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Other / Non-Disclosed</th>\n",
       "      <td>11</td>\n",
       "      <td>1.909722</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                       Gender  Percentage of Players\n",
       "Male                      484              84.027778\n",
       "Female                     81              14.062500\n",
       "Other / Non-Disclosed      11               1.909722"
      ]
     },
     "execution_count": 421,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "male_count = gender_demo.loc[\"Male\", \"Gender\"]\n",
    "female_count = gender_demo.loc[\"Female\", \"Gender\"]\n",
    "other_count = gender_demo.loc[\"Other / Non-Disclosed\", \"Gender\"]\n",
    "players = total_players.loc[\"SN\", \"Total Players\"]\n",
    "male_percent = (male_count / players) * 100\n",
    "female_percent = (female_count / players) * 100\n",
    "other_percent = (other_count / players) * 100\n",
    "percents = [male_percent, female_percent, other_percent]\n",
    "gender_demo[\"Percentage of Players\"] = percents\n",
    "gender_demo"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "\n",
    "## Purchasing Analysis (Gender)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "* Create a summary data frame to hold the results\n",
    "\n",
    "\n",
    "* Optional: give the displayed data cleaner formatting\n",
    "\n",
    "\n",
    "* Display the summary data frame"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 422,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4.468395061728395"
      ]
     },
     "execution_count": 422,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "purchase_analysis_f = purchase_data.loc[purchase_data[\"Gender\"] == \"Female\"]\n",
    "#purchase_analysis_f = purchase_analysis_f[\"Gender\"]\n",
    "purchase_count_f = purchase_analysis_f[\"Price\"].count()\n",
    "total_purchase_val_f = purchase_analysis_f[\"Price\"].sum()\n",
    "avg_price_f = total_purchase_val_f / purchase_count_f\n",
    "avg_per_f = total_purchase_val_f / female_count\n",
    "avg_per_f"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 423,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4.065371900826446"
      ]
     },
     "execution_count": 423,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "purchase_analysis_m = purchase_data.loc[purchase_data[\"Gender\"] == \"Male\"]\n",
    "#purchase_analysis_m = purchase_analysis_m[\"Gender\"]\n",
    "purchase_count_m = purchase_analysis_m[\"Price\"].count()\n",
    "total_purchase_val_m = purchase_analysis_m[\"Price\"].sum()\n",
    "avg_price_m = total_purchase_val_m / purchase_count_m\n",
    "avg_per_m = total_purchase_val_m / male_count\n",
    "avg_per_m"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 424,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4.5627272727272725"
      ]
     },
     "execution_count": 424,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "purchase_analysis_o = purchase_data.loc[purchase_data[\"Gender\"] == \n",
    "                                        \"Other / Non-Disclosed\"]\n",
    "#purchase_analysis_o = purchase_analysis_o[\"Gender\"]\n",
    "purchase_count_o = purchase_analysis_o[\"Price\"].count()\n",
    "total_purchase_val_o = purchase_analysis_o[\"Price\"].sum()\n",
    "avg_price_o = total_purchase_val_o / purchase_count_o\n",
    "avg_per_o = total_purchase_val_o / other_count\n",
    "avg_per_o"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 425,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Gender</th>\n",
       "      <th>Purchase Count</th>\n",
       "      <th>Average Purchase Price</th>\n",
       "      <th>Total Purchase Value</th>\n",
       "      <th>Average Total Purchase Per Person</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Female</td>\n",
       "      <td>113</td>\n",
       "      <td>3.203009</td>\n",
       "      <td>361.94</td>\n",
       "      <td>4.468395</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Male</td>\n",
       "      <td>652</td>\n",
       "      <td>3.017853</td>\n",
       "      <td>1967.64</td>\n",
       "      <td>4.065372</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Other / Non-Disclosed</td>\n",
       "      <td>15</td>\n",
       "      <td>3.346000</td>\n",
       "      <td>50.19</td>\n",
       "      <td>4.562727</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                  Gender  Purchase Count  Average Purchase Price  \\\n",
       "0                 Female             113                3.203009   \n",
       "1                   Male             652                3.017853   \n",
       "2  Other / Non-Disclosed              15                3.346000   \n",
       "\n",
       "   Total Purchase Value  Average Total Purchase Per Person  \n",
       "0                361.94                           4.468395  \n",
       "1               1967.64                           4.065372  \n",
       "2                 50.19                           4.562727  "
      ]
     },
     "execution_count": 425,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "purchase_count = [purchase_count_f, purchase_count_m, purchase_count_o]\n",
    "avg_price = [avg_price_f, avg_price_m, avg_price_o]\n",
    "total_purchase_val = [total_purchase_val_f, total_purchase_val_m, \n",
    "                      total_purchase_val_o]\n",
    "avg_per_person = [avg_per_f, avg_per_m, avg_per_o]\n",
    "purchase_analysis = pd.DataFrame()\n",
    "purchase_analysis[\"Gender\"] = [\"Female\", \"Male\", \"Other / Non-Disclosed\"]\n",
    "purchase_analysis[\"Purchase Count\"] = purchase_count\n",
    "purchase_analysis[\"Average Purchase Price\"] = avg_price\n",
    "purchase_analysis[\"Total Purchase Value\"] = total_purchase_val\n",
    "purchase_analysis[\"Average Total Purchase Per Person\"] = avg_per_person\n",
    "purcahse_analysis = purchase_analysis.set_index(\"Gender\")\n",
    "purchase_analysis"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Age Demographics"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "* Establish bins for ages\n",
    "\n",
    "\n",
    "* Categorize the existing players using the age bins. Hint: use pd.cut()\n",
    "\n",
    "\n",
    "* Calculate the numbers and percentages by age group\n",
    "\n",
    "\n",
    "* Create a summary data frame to hold the results\n",
    "\n",
    "\n",
    "* Optional: round the percentage column to two decimal points\n",
    "\n",
    "\n",
    "* Display Age Demographics Table\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 426,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Total Count</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>20-24</th>\n",
       "      <td>258</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15-19</th>\n",
       "      <td>107</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25-29</th>\n",
       "      <td>77</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30-34</th>\n",
       "      <td>52</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35-39</th>\n",
       "      <td>31</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10-14</th>\n",
       "      <td>22</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>&lt;10</th>\n",
       "      <td>17</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>40+</th>\n",
       "      <td>12</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       Total Count\n",
       "20-24          258\n",
       "15-19          107\n",
       "25-29           77\n",
       "30-34           52\n",
       "35-39           31\n",
       "10-14           22\n",
       "<10             17\n",
       "40+             12"
      ]
     },
     "execution_count": 426,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "player_ages = purchase_data[[\"SN\", \"Age\"]]\n",
    "player_ages = player_ages.drop_duplicates(\"SN\")\n",
    "age_demo = player_ages[\"Age\"]\n",
    "bins = [0, 9, 14, 19, 24, 29, 34, 39, 45]\n",
    "labels = ['<10', '10-14', '15-19','20-24', '25-29', '30-34', '35-39','40+']\n",
    "ages = pd.cut(age_demo, bins = bins, labels = labels)\n",
    "ages = pd.DataFrame(ages)\n",
    "ages = ages.sort_values(\"Age\")\n",
    "age_count = ages[\"Age\"].value_counts()\n",
    "age_count_df  = pd.DataFrame()\n",
    "age_count_df[\"Total Count\"] = age_count\n",
    "age_count_df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 427,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Total Count</th>\n",
       "      <th>Pecentage of Players</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>&lt;10</th>\n",
       "      <td>17</td>\n",
       "      <td>2.951389</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10-14</th>\n",
       "      <td>22</td>\n",
       "      <td>3.819444</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15-19</th>\n",
       "      <td>107</td>\n",
       "      <td>18.576389</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20-24</th>\n",
       "      <td>258</td>\n",
       "      <td>44.791667</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25-29</th>\n",
       "      <td>77</td>\n",
       "      <td>13.368056</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30-34</th>\n",
       "      <td>52</td>\n",
       "      <td>9.027778</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35-39</th>\n",
       "      <td>31</td>\n",
       "      <td>5.381944</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>40+</th>\n",
       "      <td>12</td>\n",
       "      <td>2.083333</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       Total Count  Pecentage of Players\n",
       "<10             17              2.951389\n",
       "10-14           22              3.819444\n",
       "15-19          107             18.576389\n",
       "20-24          258             44.791667\n",
       "25-29           77             13.368056\n",
       "30-34           52              9.027778\n",
       "35-39           31              5.381944\n",
       "40+             12              2.083333"
      ]
     },
     "execution_count": 427,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "player_count = total_players.loc[\"SN\", \"Total Players\"]\n",
    "age_percents = (age_count_df[\"Total Count\"] / player_count) * 100\n",
    "age_count_df[\"Pecentage of Players\"] = age_percents\n",
    "age_count_df = age_count_df.sort_index()\n",
    "age_count_df"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Purchasing Analysis (Age)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "* Bin the purchase_data data frame by age\n",
    "\n",
    "\n",
    "* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below\n",
    "\n",
    "\n",
    "* Create a summary data frame to hold the results\n",
    "\n",
    "\n",
    "* Optional: give the displayed data cleaner formatting\n",
    "\n",
    "\n",
    "* Display the summary data frame"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 451,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Age</th>\n",
       "      <th>Price</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>20</td>\n",
       "      <td>3.53</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>40</td>\n",
       "      <td>1.56</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>24</td>\n",
       "      <td>4.88</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>24</td>\n",
       "      <td>3.27</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>23</td>\n",
       "      <td>1.44</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   Age  Price\n",
       "0   20   3.53\n",
       "1   40   1.56\n",
       "2   24   4.88\n",
       "3   24   3.27\n",
       "4   23   1.44"
      ]
     },
     "execution_count": 451,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "purchasing_data_age = purchase_data[[\"Age\", \"Price\"]]\n",
    "purchasing_data_age.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 484,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Chris\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py:3: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy\n",
      "  This is separate from the ipykernel package so we can avoid doing imports until\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Age</th>\n",
       "      <th>Price</th>\n",
       "      <th>Age Ranges</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>20</td>\n",
       "      <td>3.53</td>\n",
       "      <td>20-24</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>40</td>\n",
       "      <td>1.56</td>\n",
       "      <td>40+</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>24</td>\n",
       "      <td>4.88</td>\n",
       "      <td>20-24</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>24</td>\n",
       "      <td>3.27</td>\n",
       "      <td>20-24</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>23</td>\n",
       "      <td>1.44</td>\n",
       "      <td>20-24</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   Age  Price Age Ranges\n",
       "0   20   3.53      20-24\n",
       "1   40   1.56        40+\n",
       "2   24   4.88      20-24\n",
       "3   24   3.27      20-24\n",
       "4   23   1.44      20-24"
      ]
     },
     "execution_count": 484,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "age_ranges = pd.cut(purchasing_data_age[\"Age\"], bins = bins, labels = labels)\n",
    "age_ranges.values\n",
    "purchasing_data_age[\"Age Ranges\"] = age_ranges.values\n",
    "purchasing_data_age.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 506,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Purchase Count</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>&lt;10</th>\n",
       "      <td>23</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10-14</th>\n",
       "      <td>28</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15-19</th>\n",
       "      <td>136</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20-24</th>\n",
       "      <td>365</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25-29</th>\n",
       "      <td>101</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30-34</th>\n",
       "      <td>73</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35-39</th>\n",
       "      <td>41</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>40+</th>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       Purchase Count\n",
       "<10                23\n",
       "10-14              28\n",
       "15-19             136\n",
       "20-24             365\n",
       "25-29             101\n",
       "30-34              73\n",
       "35-39              41\n",
       "40+                13"
      ]
     },
     "execution_count": 506,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "under_10_count = purchasing_data_age.loc[purchasing_data_age[\"Age Ranges\"] \n",
    "                                         ==\"<10\"]\n",
    "u_10_count = under_10_count[\"Age\"].count()\n",
    "u_10_avp = under_10_count[\"Price\"].mean()\n",
    "u_10_tpv = under_10_count[\"Price\"].sum()\n",
    "#u_10_atp = u_10_tpv / u_10_count\n",
    "count_10_14 = purchasing_data_age.loc[purchasing_data_age[\"Age Ranges\"] \n",
    "                                         == \"10-14\"]\n",
    "c_10_14 = count_10_14[\"Age\"].count()\n",
    "c_10_14_avp = count_10_14[\"Price\"].mean()\n",
    "c_10_14_tpv = count_10_14[\"Price\"].sum()\n",
    "\n",
    "count_15_19 = purchasing_data_age.loc[purchasing_data_age[\"Age Ranges\"] \n",
    "                                         == \"<15-19\"]\n",
    "c_15_19 = count_15_19[\"Age\"].count()\n",
    "c_15_19_avp = count_15_19[\"Price\"].mean()\n",
    "c_15_19_tpv = count_15_19[\"Price\"].sum()\n",
    "\n",
    "count_20_24 = purchasing_data_age.loc[purchasing_data_age[\"Age Ranges\"] \n",
    "                                         ==\"20-24\"]\n",
    "c_20_24 = count_20_24[\"Age\"].count()\n",
    "c_20_24_avp = count_20_24[\"Price\"].mean()\n",
    "c_20_24_tpv = count_20_24[\"Price\"].sum()\n",
    "\n",
    "count_25_29 = purchasing_data_age.loc[purchasing_data_age[\"Age Ranges\"] \n",
    "                                         ==\"25-29\"]\n",
    "c_25_29 = count_25_29[\"Age\"].count()\n",
    "c_25_29_avp = count_25_29[\"Price\"].mean()\n",
    "c_25_29_tpv = count_25_29[\"Price\"].sum()\n",
    "\n",
    "count_30_34 = purchasing_data_age.loc[purchasing_data_age[\"Age Ranges\"] \n",
    "                                         ==\"30-34\"]\n",
    "c_30_34 = count_30_34[\"Age\"].count()\n",
    "c_30_34_avp = count_30_34[\"Price\"].mean()\n",
    "c_30_34_tpv = count_30_34[\"Price\"].sum()\n",
    "\n",
    "count_35_39 = purchasing_data_age.loc[purchasing_data_age[\"Age Ranges\"] \n",
    "                                         ==\"35-39\"]\n",
    "c_35_39 = count_35_39[\"Age\"].count()\n",
    "c_35_39_avp = count_35_39[\"Price\"].mean()\n",
    "c_35_39_tpv = count_35_39[\"Price\"].sum()\n",
    "\n",
    "over_40_count = purchasing_data_age.loc[purchasing_data_age[\"Age Ranges\"] \n",
    "                                         ==\"40+\"]\n",
    "o_40_count = over_40_count[\"Age\"].count()\n",
    "o_40_avp = over_40_count[\"Price\"].mean()\n",
    "o_40_tpv = over_40_count[\"Price\"].sum()\n",
    "purchasing_analysis = pd.DataFrame(age_ranges.value_counts())\n",
    "purchasing_analysis = purchasing_analysis.rename(columns = {\"Age\" : \"Purchase Count\"})\n",
    "purchasing_analysis = purchasing_analysis.sort_index()\n",
    "purchasing_analysis"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 509,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Purchase Count</th>\n",
       "      <th>Average Purchase Price</th>\n",
       "      <th>Avg Total Purchase per Person</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>&lt;10</th>\n",
       "      <td>23</td>\n",
       "      <td>3.353478</td>\n",
       "      <td>77.13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10-14</th>\n",
       "      <td>28</td>\n",
       "      <td>2.956429</td>\n",
       "      <td>82.78</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15-19</th>\n",
       "      <td>136</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20-24</th>\n",
       "      <td>365</td>\n",
       "      <td>3.052219</td>\n",
       "      <td>1114.06</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25-29</th>\n",
       "      <td>101</td>\n",
       "      <td>2.900990</td>\n",
       "      <td>293.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30-34</th>\n",
       "      <td>73</td>\n",
       "      <td>2.931507</td>\n",
       "      <td>214.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35-39</th>\n",
       "      <td>41</td>\n",
       "      <td>3.601707</td>\n",
       "      <td>147.67</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>40+</th>\n",
       "      <td>13</td>\n",
       "      <td>2.941538</td>\n",
       "      <td>38.24</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       Purchase Count  Average Purchase Price  Avg Total Purchase per Person\n",
       "<10                23                3.353478                          77.13\n",
       "10-14              28                2.956429                          82.78\n",
       "15-19             136                     NaN                           0.00\n",
       "20-24             365                3.052219                        1114.06\n",
       "25-29             101                2.900990                         293.00\n",
       "30-34              73                2.931507                         214.00\n",
       "35-39              41                3.601707                         147.67\n",
       "40+                13                2.941538                          38.24"
      ]
     },
     "execution_count": 509,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "average_pp = [u_10_avp, c_10_14_avp, c_15_19_avp, c_20_24_avp, c_25_29_avp,\n",
    "              c_30_34_avp, c_35_39_avp, o_40_avp]\n",
    "total_pv = [u_10_tpv, c_10_14_tpv, c_15_19_tpv, c_20_24_tpv, c_25_29_tpv,\n",
    "             c_30_34_tpv, c_35_39_tpv, o_40_tpv]\n",
    "purchasing_analysis[\"Average Purchase Price\"] = average_pp\n",
    "purchasing_analysis[\"Avg Total Purchase per Person\"] = total_pv\n",
    "purchasing_analysis"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Top Spenders"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "* Run basic calculations to obtain the results in the table below\n",
    "\n",
    "\n",
    "* Create a summary data frame to hold the results\n",
    "\n",
    "\n",
    "* Sort the total purchase value column in descending order\n",
    "\n",
    "\n",
    "* Optional: give the displayed data cleaner formatting\n",
    "\n",
    "\n",
    "* Display a preview of the summary data frame\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 545,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Price    4.99\n",
       "dtype: float64"
      ]
     },
     "execution_count": 545,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "top_spenders = purchase_data[[\"SN\", \"Price\"]]\n",
    "by_names = top_spenders.groupby([\"SN\"])\n",
    "top_spender = by_names[\"Price\"].sum()\n",
    "avp = by_names.mean()\n",
    "tpv = top_spender.max()\n",
    "avp.max()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Most Popular Items"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "* Retrieve the Item ID, Item Name, and Item Price columns\n",
    "\n",
    "\n",
    "* Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value\n",
    "\n",
    "\n",
    "* Create a summary data frame to hold the results\n",
    "\n",
    "\n",
    "* Sort the purchase count column in descending order\n",
    "\n",
    "\n",
    "* Optional: give the displayed data cleaner formatting\n",
    "\n",
    "\n",
    "* Display a preview of the summary data frame\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 554,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>0</th>\n",
       "      <th>1</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>(0, Splinter)</td>\n",
       "      <td>Item ID Item Name  Price\n",
       "133        0  Sp...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>(1, Crucifer)</td>\n",
       "      <td>Item ID Item Name  Price\n",
       "121        1  Cr...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>(2, Verdict)</td>\n",
       "      <td>Item ID Item Name  Price\n",
       "134        2   V...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>(3, Phantomlight)</td>\n",
       "      <td>Item ID     Item Name  Price\n",
       "161        3...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>(4, Bloodlord's Fetish)</td>\n",
       "      <td>Item ID           Item Name  Price\n",
       "13    ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>(5, Putrid Fan)</td>\n",
       "      <td>Item ID   Item Name  Price\n",
       "173        5  ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>(6, Rusty Skull)</td>\n",
       "      <td>Item ID    Item Name  Price\n",
       "66         6 ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>(7, Thorn, Satchel of Dark Souls)</td>\n",
       "      <td>Item ID                     Item Name  Pr...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>(8, Purgatory, Gem of Regret)</td>\n",
       "      <td>Item ID                 Item Name  Price\n",
       "...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>(9, Thorn, Conqueror of the Corrupted)</td>\n",
       "      <td>Item ID                          Item Nam...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>(10, Sleepwalker)</td>\n",
       "      <td>Item ID    Item Name  Price\n",
       "105       10 ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>(11, Brimstone)</td>\n",
       "      <td>Item ID  Item Name  Price\n",
       "187       11  B...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>(12, Dawne)</td>\n",
       "      <td>Item ID Item Name  Price\n",
       "83        12    ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>(13, Serenity)</td>\n",
       "      <td>Item ID Item Name  Price\n",
       "115       13  Se...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>(14, Possessed Core)</td>\n",
       "      <td>Item ID       Item Name  Price\n",
       "360       ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>(15, Soul Infused Crystal)</td>\n",
       "      <td>Item ID             Item Name  Price\n",
       "51  ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>(16, Restored Bauble)</td>\n",
       "      <td>Item ID        Item Name  Price\n",
       "237      ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>(17, Lazarus, Terror of the Earth)</td>\n",
       "      <td>Item ID                     Item Name  Pr...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>(18, Torchlight, Bond of Storms)</td>\n",
       "      <td>Item ID                   Item Name  Pric...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>(19, Pursuit, Cudgel of Necromancy)</td>\n",
       "      <td>Item ID                      Item Name  P...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>(20, Netherbane)</td>\n",
       "      <td>Item ID   Item Name  Price\n",
       "77        20  ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>(21, Souleater)</td>\n",
       "      <td>Item ID  Item Name  Price\n",
       "8         21  S...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>(22, Amnesia)</td>\n",
       "      <td>Item ID Item Name  Price\n",
       "50        22   A...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>(23, Crucifer)</td>\n",
       "      <td>Item ID Item Name  Price\n",
       "251       23  Cr...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>(24, Warped Fetish)</td>\n",
       "      <td>Item ID      Item Name  Price\n",
       "22        2...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>(25, Hero Cane)</td>\n",
       "      <td>Item ID  Item Name  Price\n",
       "54        25  H...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>(26, Unholy Wand)</td>\n",
       "      <td>Item ID    Item Name  Price\n",
       "421       26 ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>(27, Riddle, Tribute of Ended Dreams)</td>\n",
       "      <td>Item ID                        Item Name  ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>(28, Flux, Destroyer of Due Diligence)</td>\n",
       "      <td>Item ID                         Item Name...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>(29, Chaos, Ender of the End)</td>\n",
       "      <td>Item ID                Item Name  Price\n",
       "7...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>153</th>\n",
       "      <td>(154, Feral Katana)</td>\n",
       "      <td>Item ID     Item Name  Price\n",
       "182      154...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>154</th>\n",
       "      <td>(155, War-Forged Gold Deflector)</td>\n",
       "      <td>Item ID                  Item Name  Price...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>155</th>\n",
       "      <td>(156, Soul-Forged Steel Shortsword)</td>\n",
       "      <td>Item ID                     Item Name  Pr...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>156</th>\n",
       "      <td>(157, Spada, Etcher of Hatred)</td>\n",
       "      <td>Item ID                Item Name  Price\n",
       "1...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>157</th>\n",
       "      <td>(158, Darkheart, Butcher of the Champion)</td>\n",
       "      <td>Item ID                           Item Na...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>158</th>\n",
       "      <td>(159, Oathbreaker, Spellblade of Trials)</td>\n",
       "      <td>Item ID                          Item Nam...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>159</th>\n",
       "      <td>(160, Azurewrath)</td>\n",
       "      <td>Item ID   Item Name  Price\n",
       "34       160  ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>160</th>\n",
       "      <td>(161, Devine)</td>\n",
       "      <td>Item ID Item Name  Price\n",
       "17       161    ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>161</th>\n",
       "      <td>(162, Abyssal Shard)</td>\n",
       "      <td>Item ID      Item Name  Price\n",
       "7        16...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>162</th>\n",
       "      <td>(163, Thunderfury Scimitar)</td>\n",
       "      <td>Item ID             Item Name  Price\n",
       "235 ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>163</th>\n",
       "      <td>(164, Exiled Doomblade)</td>\n",
       "      <td>Item ID         Item Name  Price\n",
       "95      ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>164</th>\n",
       "      <td>(165, Bone Crushing Silver Skewer)</td>\n",
       "      <td>Item ID                    Item Name  Pri...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>165</th>\n",
       "      <td>(166, Thirsty Iron Reaver)</td>\n",
       "      <td>Item ID            Item Name  Price\n",
       "271  ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>166</th>\n",
       "      <td>(167, Malice, Legacy of the Queen)</td>\n",
       "      <td>Item ID                    Item Name  Pri...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>167</th>\n",
       "      <td>(168, Sun Strike, Jaws of Twisted Visions)</td>\n",
       "      <td>Item ID                            Item N...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>168</th>\n",
       "      <td>(169, Interrogator, Blood Blade of the Queen)</td>\n",
       "      <td>Item ID                               Ite...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>169</th>\n",
       "      <td>(170, Shadowsteel)</td>\n",
       "      <td>Item ID    Item Name  Price\n",
       "47       170 ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>170</th>\n",
       "      <td>(171, Scalpel)</td>\n",
       "      <td>Item ID Item Name  Price\n",
       "294      171   S...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>171</th>\n",
       "      <td>(172, Blade of the Grave)</td>\n",
       "      <td>Item ID           Item Name  Price\n",
       "39    ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>172</th>\n",
       "      <td>(173, Stormfury Longsword)</td>\n",
       "      <td>Item ID            Item Name  Price\n",
       "275  ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>173</th>\n",
       "      <td>(174, Primitive Blade)</td>\n",
       "      <td>Item ID        Item Name  Price\n",
       "81       ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>174</th>\n",
       "      <td>(175, Woeful Adamantite Claymore)</td>\n",
       "      <td>Item ID                   Item Name  Pric...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>175</th>\n",
       "      <td>(176, Relentless Iron Skewer)</td>\n",
       "      <td>Item ID               Item Name  Price\n",
       "53...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>176</th>\n",
       "      <td>(177, Winterthorn, Defender of Shifting Worlds)</td>\n",
       "      <td>Item ID                                 I...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>177</th>\n",
       "      <td>(178, Oathbreaker, Last Hope of the Breaking S...</td>\n",
       "      <td>Item ID                                  ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>178</th>\n",
       "      <td>(179, Wolf, Promise of the Moonwalker)</td>\n",
       "      <td>Item ID                        Item Name ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>179</th>\n",
       "      <td>(180, Stormcaller)</td>\n",
       "      <td>Item ID    Item Name  Price\n",
       "751      180 ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>180</th>\n",
       "      <td>(181, Reaper's Toll)</td>\n",
       "      <td>Item ID      Item Name  Price\n",
       "45       18...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>181</th>\n",
       "      <td>(182, Toothpick)</td>\n",
       "      <td>Item ID  Item Name  Price\n",
       "256      182  T...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>182</th>\n",
       "      <td>(183, Dragon's Greatsword)</td>\n",
       "      <td>Item ID            Item Name  Price\n",
       "165  ...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>183 rows × 2 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                     0  \\\n",
       "0                                        (0, Splinter)   \n",
       "1                                        (1, Crucifer)   \n",
       "2                                         (2, Verdict)   \n",
       "3                                    (3, Phantomlight)   \n",
       "4                              (4, Bloodlord's Fetish)   \n",
       "5                                      (5, Putrid Fan)   \n",
       "6                                     (6, Rusty Skull)   \n",
       "7                    (7, Thorn, Satchel of Dark Souls)   \n",
       "8                        (8, Purgatory, Gem of Regret)   \n",
       "9               (9, Thorn, Conqueror of the Corrupted)   \n",
       "10                                   (10, Sleepwalker)   \n",
       "11                                     (11, Brimstone)   \n",
       "12                                         (12, Dawne)   \n",
       "13                                      (13, Serenity)   \n",
       "14                                (14, Possessed Core)   \n",
       "15                          (15, Soul Infused Crystal)   \n",
       "16                               (16, Restored Bauble)   \n",
       "17                  (17, Lazarus, Terror of the Earth)   \n",
       "18                    (18, Torchlight, Bond of Storms)   \n",
       "19                 (19, Pursuit, Cudgel of Necromancy)   \n",
       "20                                    (20, Netherbane)   \n",
       "21                                     (21, Souleater)   \n",
       "22                                       (22, Amnesia)   \n",
       "23                                      (23, Crucifer)   \n",
       "24                                 (24, Warped Fetish)   \n",
       "25                                     (25, Hero Cane)   \n",
       "26                                   (26, Unholy Wand)   \n",
       "27               (27, Riddle, Tribute of Ended Dreams)   \n",
       "28              (28, Flux, Destroyer of Due Diligence)   \n",
       "29                       (29, Chaos, Ender of the End)   \n",
       "..                                                 ...   \n",
       "153                                (154, Feral Katana)   \n",
       "154                   (155, War-Forged Gold Deflector)   \n",
       "155                (156, Soul-Forged Steel Shortsword)   \n",
       "156                     (157, Spada, Etcher of Hatred)   \n",
       "157          (158, Darkheart, Butcher of the Champion)   \n",
       "158           (159, Oathbreaker, Spellblade of Trials)   \n",
       "159                                  (160, Azurewrath)   \n",
       "160                                      (161, Devine)   \n",
       "161                               (162, Abyssal Shard)   \n",
       "162                        (163, Thunderfury Scimitar)   \n",
       "163                            (164, Exiled Doomblade)   \n",
       "164                 (165, Bone Crushing Silver Skewer)   \n",
       "165                         (166, Thirsty Iron Reaver)   \n",
       "166                 (167, Malice, Legacy of the Queen)   \n",
       "167         (168, Sun Strike, Jaws of Twisted Visions)   \n",
       "168      (169, Interrogator, Blood Blade of the Queen)   \n",
       "169                                 (170, Shadowsteel)   \n",
       "170                                     (171, Scalpel)   \n",
       "171                          (172, Blade of the Grave)   \n",
       "172                         (173, Stormfury Longsword)   \n",
       "173                             (174, Primitive Blade)   \n",
       "174                  (175, Woeful Adamantite Claymore)   \n",
       "175                      (176, Relentless Iron Skewer)   \n",
       "176    (177, Winterthorn, Defender of Shifting Worlds)   \n",
       "177  (178, Oathbreaker, Last Hope of the Breaking S...   \n",
       "178             (179, Wolf, Promise of the Moonwalker)   \n",
       "179                                 (180, Stormcaller)   \n",
       "180                               (181, Reaper's Toll)   \n",
       "181                                   (182, Toothpick)   \n",
       "182                         (183, Dragon's Greatsword)   \n",
       "\n",
       "                                                     1  \n",
       "0         Item ID Item Name  Price\n",
       "133        0  Sp...  \n",
       "1         Item ID Item Name  Price\n",
       "121        1  Cr...  \n",
       "2         Item ID Item Name  Price\n",
       "134        2   V...  \n",
       "3         Item ID     Item Name  Price\n",
       "161        3...  \n",
       "4         Item ID           Item Name  Price\n",
       "13    ...  \n",
       "5         Item ID   Item Name  Price\n",
       "173        5  ...  \n",
       "6         Item ID    Item Name  Price\n",
       "66         6 ...  \n",
       "7         Item ID                     Item Name  Pr...  \n",
       "8         Item ID                 Item Name  Price\n",
       "...  \n",
       "9         Item ID                          Item Nam...  \n",
       "10        Item ID    Item Name  Price\n",
       "105       10 ...  \n",
       "11        Item ID  Item Name  Price\n",
       "187       11  B...  \n",
       "12        Item ID Item Name  Price\n",
       "83        12    ...  \n",
       "13        Item ID Item Name  Price\n",
       "115       13  Se...  \n",
       "14        Item ID       Item Name  Price\n",
       "360       ...  \n",
       "15        Item ID             Item Name  Price\n",
       "51  ...  \n",
       "16        Item ID        Item Name  Price\n",
       "237      ...  \n",
       "17        Item ID                     Item Name  Pr...  \n",
       "18        Item ID                   Item Name  Pric...  \n",
       "19        Item ID                      Item Name  P...  \n",
       "20        Item ID   Item Name  Price\n",
       "77        20  ...  \n",
       "21        Item ID  Item Name  Price\n",
       "8         21  S...  \n",
       "22        Item ID Item Name  Price\n",
       "50        22   A...  \n",
       "23        Item ID Item Name  Price\n",
       "251       23  Cr...  \n",
       "24        Item ID      Item Name  Price\n",
       "22        2...  \n",
       "25        Item ID  Item Name  Price\n",
       "54        25  H...  \n",
       "26        Item ID    Item Name  Price\n",
       "421       26 ...  \n",
       "27       Item ID                        Item Name  ...  \n",
       "28        Item ID                         Item Name...  \n",
       "29        Item ID                Item Name  Price\n",
       "7...  \n",
       "..                                                 ...  \n",
       "153       Item ID     Item Name  Price\n",
       "182      154...  \n",
       "154       Item ID                  Item Name  Price...  \n",
       "155       Item ID                     Item Name  Pr...  \n",
       "156       Item ID                Item Name  Price\n",
       "1...  \n",
       "157       Item ID                           Item Na...  \n",
       "158       Item ID                          Item Nam...  \n",
       "159       Item ID   Item Name  Price\n",
       "34       160  ...  \n",
       "160       Item ID Item Name  Price\n",
       "17       161    ...  \n",
       "161       Item ID      Item Name  Price\n",
       "7        16...  \n",
       "162       Item ID             Item Name  Price\n",
       "235 ...  \n",
       "163       Item ID         Item Name  Price\n",
       "95      ...  \n",
       "164       Item ID                    Item Name  Pri...  \n",
       "165       Item ID            Item Name  Price\n",
       "271  ...  \n",
       "166       Item ID                    Item Name  Pri...  \n",
       "167       Item ID                            Item N...  \n",
       "168       Item ID                               Ite...  \n",
       "169       Item ID    Item Name  Price\n",
       "47       170 ...  \n",
       "170       Item ID Item Name  Price\n",
       "294      171   S...  \n",
       "171       Item ID           Item Name  Price\n",
       "39    ...  \n",
       "172       Item ID            Item Name  Price\n",
       "275  ...  \n",
       "173       Item ID        Item Name  Price\n",
       "81       ...  \n",
       "174       Item ID                   Item Name  Pric...  \n",
       "175       Item ID               Item Name  Price\n",
       "53...  \n",
       "176       Item ID                                 I...  \n",
       "177       Item ID                                  ...  \n",
       "178       Item ID                        Item Name ...  \n",
       "179       Item ID    Item Name  Price\n",
       "751      180 ...  \n",
       "180       Item ID      Item Name  Price\n",
       "45       18...  \n",
       "181       Item ID  Item Name  Price\n",
       "256      182  T...  \n",
       "182       Item ID            Item Name  Price\n",
       "165  ...  \n",
       "\n",
       "[183 rows x 2 columns]"
      ]
     },
     "execution_count": 554,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "most_popular = purchase_data[[\"Item ID\", \"Item Name\", \"Price\"]]\n",
    "most_popular = most_popular.groupby([\"Item ID\", \"Item Name\"])\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Most Profitable Items"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "* Sort the above table by total purchase value in descending order\n",
    "\n",
    "\n",
    "* Optional: give the displayed data cleaner formatting\n",
    "\n",
    "\n",
    "* Display a preview of the data frame\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th>Purchase Count</th>\n",
       "      <th>Item Price</th>\n",
       "      <th>Total Purchase Value</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Item ID</th>\n",
       "      <th>Item Name</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>178</th>\n",
       "      <th>Oathbreaker, Last Hope of the Breaking Storm</th>\n",
       "      <td>12</td>\n",
       "      <td>$4.23</td>\n",
       "      <td>$50.76</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>82</th>\n",
       "      <th>Nirvana</th>\n",
       "      <td>9</td>\n",
       "      <td>$4.90</td>\n",
       "      <td>$44.10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>145</th>\n",
       "      <th>Fiery Glass Crusader</th>\n",
       "      <td>9</td>\n",
       "      <td>$4.58</td>\n",
       "      <td>$41.22</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>92</th>\n",
       "      <th>Final Critic</th>\n",
       "      <td>8</td>\n",
       "      <td>$4.88</td>\n",
       "      <td>$39.04</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>103</th>\n",
       "      <th>Singed Scalpel</th>\n",
       "      <td>8</td>\n",
       "      <td>$4.35</td>\n",
       "      <td>$34.80</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                     Purchase Count  \\\n",
       "Item ID Item Name                                                     \n",
       "178     Oathbreaker, Last Hope of the Breaking Storm             12   \n",
       "82      Nirvana                                                   9   \n",
       "145     Fiery Glass Crusader                                      9   \n",
       "92      Final Critic                                              8   \n",
       "103     Singed Scalpel                                            8   \n",
       "\n",
       "                                                     Item Price  \\\n",
       "Item ID Item Name                                                 \n",
       "178     Oathbreaker, Last Hope of the Breaking Storm      $4.23   \n",
       "82      Nirvana                                           $4.90   \n",
       "145     Fiery Glass Crusader                              $4.58   \n",
       "92      Final Critic                                      $4.88   \n",
       "103     Singed Scalpel                                    $4.35   \n",
       "\n",
       "                                                     Total Purchase Value  \n",
       "Item ID Item Name                                                          \n",
       "178     Oathbreaker, Last Hope of the Breaking Storm               $50.76  \n",
       "82      Nirvana                                                    $44.10  \n",
       "145     Fiery Glass Crusader                                       $41.22  \n",
       "92      Final Critic                                               $39.04  \n",
       "103     Singed Scalpel                                             $34.80  "
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": []
  }
 ],
 "metadata": {
  "anaconda-cloud": {},
  "kernel_info": {
   "name": "python3"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.0"
  },
  "nteract": {
   "version": "0.2.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
